name: Build .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output ./bin/Release/net6.0/publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./bin/Release/net6.0/publish/
